<?php

return [
  "currencies"=>
[
["currency_id"=> "1","country_name"=> 'Afghanistan',"currency_name"=> 'Afghan afghani',"code"=> 'AFN',"symbol"=> "؋"],
["currency_id"=> "2","country_name"=> 'Akrotiri and Dhekelia (UK)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "3","country_name"=> 'Aland Islands (Finland)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "4","country_name"=> 'Albania',"currency_name"=> 'Albanian lek',"code"=> 'ALL',"symbol"=> "L"],
["currency_id"=> "5","country_name"=> 'Algeria',"currency_name"=> 'Algerian dinar',"code"=> 'DZD',"symbol"=> "د.ج"],
["currency_id"=> "6","country_name"=> 'American Samoa (USA)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "7","country_name"=> 'Andorra',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "8","country_name"=> 'Angola',"currency_name"=> 'Angolan kwanza',"code"=> 'AOA',"symbol"=> "Kz"],
["currency_id"=> "9","country_name"=> 'Anguilla (UK)',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "$"],
["currency_id"=> "10","country_name"=> 'Antigua and Barbuda',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "$"],
["currency_id"=> "11","country_name"=> 'Argentina',"currency_name"=> 'Argentine peso',"code"=> 'ARS',"symbol"=> "$"],
["currency_id"=> "12","country_name"=> 'Armenia',"currency_name"=> 'Armenian dram',"code"=> 'AMD',"symbol"=> "Դ"],
["currency_id"=> "13","country_name"=> 'Aruba (Netherlands)',"currency_name"=> 'Aruban florin',"code"=> 'AWG',"symbol"=> "ƒ"],
["currency_id"=> "14","country_name"=> 'Ascension Island (UK)',"currency_name"=> 'Saint Helena pound',"code"=> 'SHP',"symbol"=> "£"],
["currency_id"=> "15","country_name"=> 'Australia',"currency_name"=> 'Australian dollar',"code"=> 'AUD',"symbol"=> "$"],
["currency_id"=> "16","country_name"=> 'Austria',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "17","country_name"=> 'Azerbaijan',"currency_name"=> 'Azerbaijan manat',"code"=> 'AZN',"symbol"=> "ман"],
["currency_id"=> "18","country_name"=> 'Bahamas',"currency_name"=> 'Bahamian dollar',"code"=> 'BSD',"symbol"=> "$"],
["currency_id"=> "19","country_name"=> 'Bahrain',"currency_name"=> 'Bahraini dinar',"code"=> 'BHD',"symbol"=> "ب.د"],
["currency_id"=> "20","country_name"=> 'Bangladesh',"currency_name"=> 'Bangladeshi taka',"code"=> 'BDT',"symbol"=> "৳"],
["currency_id"=> "21","country_name"=> 'Barbados',"currency_name"=> 'Barbadian dollar',"code"=> 'BBD',"symbol"=> "$"],
["currency_id"=> "22","country_name"=> 'Belarus',"currency_name"=> 'Belarusian ruble',"code"=> 'BYN',"symbol"=> "Br"],
["currency_id"=> "23","country_name"=> 'Belgium',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "24","country_name"=> 'Belize',"currency_name"=> 'Belize dollar',"code"=> 'BZD',"symbol"=> "$"],
["currency_id"=> "25","country_name"=> 'Benin',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "26","country_name"=> 'Bermuda (UK)',"currency_name"=> 'Bermudian dollar',"code"=> 'BMD',"symbol"=> "$"],
["currency_id"=> "27","country_name"=> 'Bhutan',"currency_name"=> 'Bhutanese ngultrum',"code"=> 'BTN',"symbol"=> "Nu."],
["currency_id"=> "28","country_name"=> 'Bolivia',"currency_name"=> 'Bolivian boliviano',"code"=> 'BOB',"symbol"=> "Bs."],
["currency_id"=> "29","country_name"=> 'Bonaire (Netherlands)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "30","country_name"=> 'Bosnia and Herzegovina',"currency_name"=> 'Bosnia and Herzegovina convertible mark',"code"=> 'BAM',"symbol"=> "КМ"],
["currency_id"=> "31","country_name"=> 'Botswana',"currency_name"=> 'Botswana pula',"code"=> 'BWP',"symbol"=> "P"],
["currency_id"=> "32","country_name"=> 'Brazil',"currency_name"=> 'Brazilian real',"code"=> 'BRL',"symbol"=> "R$"],
["currency_id"=> "33","country_name"=> 'British Indian Ocean Territory (UK)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "34","country_name"=> 'British Virgin Islands (UK)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "35","country_name"=> 'Brunei',"currency_name"=> 'Brunei dollar',"code"=> 'BND',"symbol"=> "$"],
["currency_id"=> "36","country_name"=> 'Bulgaria',"currency_name"=> 'Bulgarian lev',"code"=> 'BGN',"symbol"=> "лв"],
["currency_id"=> "37","country_name"=> 'Burkina Faso',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "38","country_name"=> 'Burundi',"currency_name"=> 'Burundi franc',"code"=> 'BIF',"symbol"=> "₣"],
["currency_id"=> "39","country_name"=> 'Cabo Verde',"currency_name"=> 'Cape Verdean escudo',"code"=> 'CVE',"symbol"=> "$"],
["currency_id"=> "40","country_name"=> 'Cambodia',"currency_name"=> 'Cambodian riel',"code"=> 'KHR',"symbol"=> "៛"],
["currency_id"=> "41","country_name"=> 'Cameroon',"currency_name"=> 'Central African CFA franc',"code"=> 'XAF',"symbol"=> "₣"],
["currency_id"=> "42","country_name"=> 'Canada',"currency_name"=> 'Canadian dollar',"code"=> 'CAD',"symbol"=> "$"],
["currency_id"=> "43","country_name"=> 'Caribbean Netherlands (Netherlands)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "44","country_name"=> 'Cayman Islands (UK)',"currency_name"=> 'Cayman Islands dollar',"code"=> 'KYD',"symbol"=> "$"],
["currency_id"=> "45","country_name"=> 'Central African Republic',"currency_name"=> 'Central African CFA franc',"code"=> 'XAF',"symbol"=> "₣"],
["currency_id"=> "46","country_name"=> 'Chad',"currency_name"=> 'Central African CFA franc',"code"=> 'XAF',"symbol"=> "₣"],
["currency_id"=> "47","country_name"=> 'Chatham Islands (New Zealand)',"currency_name"=> 'New Zealand dollar',"code"=> 'NZD',"symbol"=> "$"],
["currency_id"=> "48","country_name"=> 'Chile',"currency_name"=> 'Chilean peso',"code"=> 'CLP',"symbol"=> "1"],
["currency_id"=> "49","country_name"=> 'China',"currency_name"=> 'Chinese Yuan Renminbi',"code"=> 'CNY',"symbol"=> "¥"],
["currency_id"=> "50","country_name"=> 'Christmas Island (Australia)',"currency_name"=> 'Australian dollar',"code"=> 'AUD',"symbol"=> "$"],
["currency_id"=> "51","country_name"=> 'Cocos (Keeling) Islands (Australia)',"currency_name"=> 'Australian dollar',"code"=> 'AUD',"symbol"=> "$"],
["currency_id"=> "52","country_name"=> 'Colombia',"currency_name"=> 'Colombian peso',"code"=> 'COP',"symbol"=> "COP"],
["currency_id"=> "53","country_name"=> 'Comoros',"currency_name"=> 'Comorian franc',"code"=> 'KMF',"symbol"=> "CF"],
["currency_id"=> "54","country_name"=> 'Congo Democratic Republic of the',"currency_name"=> 'Congolese franc',"code"=> 'CDF',"symbol"=> "₣"],
["currency_id"=> "55","country_name"=> 'Congo Republic of the',"currency_name"=> 'Central African CFA franc',"code"=> 'XAF',"symbol"=> "₣"],
["currency_id"=> "56","country_name"=> 'Cook Islands (New Zealand)',"currency_name"=> 'Cook Islands dollar',"code"=> 'NZD',"symbol"=> "$"],
["currency_id"=> "57","country_name"=> 'Costa Rica',"currency_name"=> 'Costa Rican colon',"code"=> 'CRC',"symbol"=> "₡"],
["currency_id"=> "58","country_name"=> 'Cote d Ivoire',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "59","country_name"=> 'Croatia',"currency_name"=> 'Croatian kuna',"code"=> 'HRK',"symbol"=> "Kn"],
["currency_id"=> "60","country_name"=> 'Cuba',"currency_name"=> 'Cuban peso',"code"=> 'CUP',"symbol"=> "₱"],
["currency_id"=> "61","country_name"=> 'Curacao (Netherlands)',"currency_name"=> 'Netherlands Antillean guilder',"code"=> 'ANG',"symbol"=> "ƒ"],
["currency_id"=> "62","country_name"=> 'Cyprus',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "63","country_name"=> 'Czechia',"currency_name"=> 'Czech koruna',"code"=> 'CZK',"symbol"=> "Kč"],
["currency_id"=> "64","country_name"=> 'Denmark',"currency_name"=> 'Danish krone',"code"=> 'DKK',"symbol"=> "kr"],
["currency_id"=> "65","country_name"=> 'Djibouti',"currency_name"=> 'Djiboutian franc',"code"=> 'DJF',"symbol"=> "₣"],
["currency_id"=> "66","country_name"=> 'Dominica',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "$"],
["currency_id"=> "67","country_name"=> 'Dominican Republic',"currency_name"=> 'Dominican peso',"code"=> 'DOP',"symbol"=> "$"],
["currency_id"=> "68","country_name"=> 'Ecuador',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "69","country_name"=> 'Egypt',"currency_name"=> 'Egyptian pound',"code"=> 'EGP',"symbol"=> "£"],
["currency_id"=> "70","country_name"=> 'El Salvador',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "71","country_name"=> 'Equatorial Guinea',"currency_name"=> 'Central African CFA franc',"code"=> 'XAF',"symbol"=> "₣"],
["currency_id"=> "72","country_name"=> 'Eritrea',"currency_name"=> 'Eritrean nakfa',"code"=> 'ERN',"symbol"=> "Nfk"],
["currency_id"=> "73","country_name"=> 'Estonia',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "74","country_name"=> 'Eswatini (formerly Swaziland)',"currency_name"=> 'Swazi lilangeni',"code"=> 'SZL',"symbol"=> "L"],
["currency_id"=> "75","country_name"=> 'Ethiopia',"currency_name"=> 'Ethiopian birr',"code"=> 'ETB',"symbol"=> "ብር"],
["currency_id"=> "76","country_name"=> 'Falkland Islands (UK)',"currency_name"=> 'Falkland Islands pound',"code"=> 'FKP',"symbol"=> "£"],
["currency_id"=> "77","country_name"=> 'Faroe Islands (Denmark)',"currency_name"=> 'Faroese krona',"code"=> 'NZD',"symbol"=> "$"],
["currency_id"=> "78","country_name"=> 'Fiji',"currency_name"=> 'Fijian dollar',"code"=> 'FJD',"symbol"=> "$"],
["currency_id"=> "79","country_name"=> 'Finland',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "80","country_name"=> 'France',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "81","country_name"=> 'French Guiana (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "82","country_name"=> 'French Polynesia (France)',"currency_name"=> 'CFP franc',"code"=> 'XPF',"symbol"=> "₣"],
["currency_id"=> "83","country_name"=> 'Gabon',"currency_name"=> 'Central African CFA franc',"code"=> 'XAF',"symbol"=> "₣"],
["currency_id"=> "84","country_name"=> 'Gambia',"currency_name"=> 'Gambian dalasi',"code"=> 'GMD',"symbol"=> "D"],
["currency_id"=> "85","country_name"=> 'Georgia',"currency_name"=> 'Georgian lari',"code"=> 'GEL',"symbol"=> "ლ"],
["currency_id"=> "86","country_name"=> 'Germany',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "87","country_name"=> 'Ghana',"currency_name"=> 'Ghanaian cedi',"code"=> 'GHS',"symbol"=> "₵"],
["currency_id"=> "88","country_name"=> 'Gibraltar (UK)',"currency_name"=> 'Gibraltar pound',"code"=> 'GIP',"symbol"=> "£"],
["currency_id"=> "89","country_name"=> 'Greece',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "90","country_name"=> 'Greenland (Denmark)',"currency_name"=> 'Danish krone',"code"=> 'DKK',"symbol"=> "kr"],
["currency_id"=> "91","country_name"=> 'Grenada',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "$"],
["currency_id"=> "92","country_name"=> 'Guadeloupe (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "93","country_name"=> 'Guam (USA)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "94","country_name"=> 'Guatemala',"currency_name"=> 'Guatemalan quetzal',"code"=> 'GTQ',"symbol"=> "Q"],
["currency_id"=> "95","country_name"=> 'Guernsey (UK)',"currency_name"=> 'Guernsey Pound',"code"=> 'GGP',"symbol"=> "£"],
["currency_id"=> "96","country_name"=> 'Guinea',"currency_name"=> 'Guinean franc',"code"=> 'GNF',"symbol"=> "₣"],
["currency_id"=> "97","country_name"=> 'Guinea-Bissau',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "98","country_name"=> 'Guyana',"currency_name"=> 'Guyanese dollar',"code"=> 'GYD',"symbol"=> "$"],
["currency_id"=> "99","country_name"=> 'Haiti',"currency_name"=> 'Haitian gourde',"code"=> 'HTG',"symbol"=> "G"],
["currency_id"=> "100","country_name"=> 'Honduras',"currency_name"=> 'Honduran lempira',"code"=> 'HNL',"symbol"=> "L"],
["currency_id"=> "101","country_name"=> 'Hong Kong (China)',"currency_name"=> 'Hong Kong dollar',"code"=> 'HKD',"symbol"=> "$"],
["currency_id"=> "102","country_name"=> 'Hungary',"currency_name"=> 'Hungarian forint',"code"=> 'HUF',"symbol"=> "Ft"],
["currency_id"=> "103","country_name"=> 'Iceland',"currency_name"=> 'Icelandic krona',"code"=> 'ISK',"symbol"=> "Kr"],
["currency_id"=> "104","country_name"=> 'India',"currency_name"=> 'Indian rupee',"code"=> 'INR',"symbol"=> "₹"],
["currency_id"=> "105","country_name"=> 'Indonesia',"currency_name"=> 'Indonesian rupiah',"code"=> 'IDR',"symbol"=> "Rp"],
["currency_id"=> "106","country_name"=> 'International Monetary Fund (IMF)',"currency_name"=> 'SDR (Special Drawing Right)',"code"=> 'XDR',"symbol"=> "SDR"],
["currency_id"=> "107","country_name"=> 'Iran',"currency_name"=> 'Iranian rial',"code"=> 'IRR',"symbol"=> "﷼"],
["currency_id"=> "108","country_name"=> 'Iraq',"currency_name"=> 'Iraqi dinar',"code"=> 'IQD',"symbol"=> "ع.د"],
["currency_id"=> "109","country_name"=> 'Ireland',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "110","country_name"=> 'Isle of Man (UK)',"currency_name"=> 'Manx pound',"code"=> 'IMP',"symbol"=> "£"],
["currency_id"=> "111","country_name"=> 'Israel',"currency_name"=> 'Israeli new shekel',"code"=> 'ILS',"symbol"=> "₪"],
["currency_id"=> "112","country_name"=> 'Italy',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "113","country_name"=> 'Jamaica',"currency_name"=> 'Jamaican dollar',"code"=> 'JMD',"symbol"=> "$"],
["currency_id"=> "114","country_name"=> 'Japan',"currency_name"=> 'Japanese yen',"code"=> 'JPY',"symbol"=> "¥"],
["currency_id"=> "115","country_name"=> 'Jersey (UK)',"currency_name"=> 'Jersey pound',"code"=> 'JEP',"symbol"=> "£"],
["currency_id"=> "116","country_name"=> 'Jordan',"currency_name"=> 'Jordanian dinar',"code"=> 'JOD',"symbol"=> "د.ا"],
["currency_id"=> "117","country_name"=> 'Kazakhstan',"currency_name"=> 'Kazakhstani tenge',"code"=> 'KZT',"symbol"=> "〒"],
["currency_id"=> "118","country_name"=> 'Kenya',"currency_name"=> 'Kenyan shilling',"code"=> 'KES',"symbol"=> "Ksh"],
["currency_id"=> "119","country_name"=> 'Kiribati',"currency_name"=> 'Australian dollar',"code"=> 'AUD',"symbol"=> "$"],
["currency_id"=> "120","country_name"=> 'Kosovo',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "121","country_name"=> 'Kuwait',"currency_name"=> 'Kuwaiti dinar',"code"=> 'KWD',"symbol"=> "د.ك"],
["currency_id"=> "122","country_name"=> 'Kyrgyzstan',"currency_name"=> 'Kyrgyzstani som',"code"=> 'KGS',"symbol"=> "Лв"],
["currency_id"=> "123","country_name"=> 'Laos',"currency_name"=> 'Lao kip',"code"=> 'LAK',"symbol"=> "₭"],
["currency_id"=> "124","country_name"=> 'Latvia',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "125","country_name"=> 'Lebanon',"currency_name"=> 'Lebanese pound',"code"=> 'LBP',"symbol"=> "£"],
["currency_id"=> "126","country_name"=> 'Lesotho',"currency_name"=> 'Lesotho loti',"code"=> 'LSL',"symbol"=> "L"],
["currency_id"=> "127","country_name"=> 'Liberia',"currency_name"=> 'Liberian dollar',"code"=> 'LRD',"symbol"=> "$"],
["currency_id"=> "128","country_name"=> 'Libya',"currency_name"=> 'Libyan dinar',"code"=> 'LYD',"symbol"=> "ل.د"],
["currency_id"=> "129","country_name"=> 'Liechtenstein',"currency_name"=> 'Swiss franc',"code"=> 'CHF',"symbol"=> "₣"],
["currency_id"=> "130","country_name"=> 'Lithuania',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "131","country_name"=> 'Luxembourg',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "132","country_name"=> 'Macau (China)',"currency_name"=> 'Macanese pataca',"code"=> 'MOP',"symbol"=> "P"],
["currency_id"=> "133","country_name"=> 'Madagascar',"currency_name"=> 'Malagasy ariary',"code"=> 'MGA',"symbol"=> "Ar"],
["currency_id"=> "134","country_name"=> 'Malawi',"currency_name"=> 'Malawian kwacha',"code"=> 'MWK',"symbol"=> "MK"],
["currency_id"=> "135","country_name"=> 'Malaysia',"currency_name"=> 'Malaysian ringgit',"code"=> 'MYR',"symbol"=> "RM"],
["currency_id"=> "136","country_name"=> 'Maldives',"currency_name"=> 'Maldivian rufiyaa',"code"=> 'MVR',"symbol"=> "ރ."],
["currency_id"=> "137","country_name"=> 'Mali',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "138","country_name"=> 'Malta',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "139","country_name"=> 'Marshall Islands',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "140","country_name"=> 'Martinique (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "141","country_name"=> 'Mauritania',"currency_name"=> 'Mauritanian ouguiya',"code"=>'MRU',"symbol"=> "UM"],
["currency_id"=> "142","country_name"=> 'Mauritius',"currency_name"=> 'Mauritian rupee',"code"=>'MUR',"symbol"=> "₨"],
["currency_id"=> "143","country_name"=> 'Mayotte (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "144","country_name"=> 'Mexico',"currency_name"=> 'Mexican peso',"code"=>'MXN',"symbol"=> "$"],
["currency_id"=> "145","country_name"=> 'Micronesia',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "146","country_name"=> 'Moldova',"currency_name"=> 'Moldovan leu',"code"=> 'MDL',"symbol"=> "L"],
["currency_id"=> "147","country_name"=> 'Monaco',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "148","country_name"=> 'Mongolia',"currency_name"=> 'Mongolian tugrik',"code"=> 'MNT',"symbol"=> "₮"],
["currency_id"=> "149","country_name"=> 'Montenegro',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "150","country_name"=> 'Montserrat (UK)',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "$"],
["currency_id"=> "151","country_name"=> 'Morocco',"currency_name"=> 'Moroccan dirham',"code"=> 'MAD',"symbol"=> "د.م."],
["currency_id"=> "152","country_name"=> 'Mozambique',"currency_name"=> 'Mozambican metical',"code"=> 'MZN',"symbol"=> "MTn"],
["currency_id"=> "153","country_name"=> 'Myanmar (formerly Burma)',"currency_name"=> 'Myanmar kyat',"code"=> 'MMK',"symbol"=> "K"],
["currency_id"=> "154","country_name"=> 'Namibia',"currency_name"=> 'Namibian dollar',"code"=> 'NAD',"symbol"=> "$"],
["currency_id"=> "155","country_name"=> 'Nauru',"currency_name"=> 'Australian dollar',"code"=> 'AUD',"symbol"=> "$"],
["currency_id"=> "156","country_name"=> 'Nepal',"currency_name"=> 'Nepalese rupee',"code"=> 'NPR',"symbol"=> "₨"],
["currency_id"=> "157","country_name"=> 'Netherlands',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "158","country_name"=> 'New Caledonia (France)',"currency_name"=> 'CFP franc',"code"=> 'XPF',"symbol"=> "₣"],
["currency_id"=> "159","country_name"=> 'New Zealand',"currency_name"=> 'New Zealand dollar',"code"=> 'NZD',"symbol"=> "$"],
["currency_id"=> "160","country_name"=> 'Nicaragua',"currency_name"=> 'Nicaraguan cordoba',"code"=> 'NIO',"symbol"=> "C$"],
["currency_id"=> "161","country_name"=> 'Niger',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "162","country_name"=> 'Nigeria',"currency_name"=> 'Nigerian naira',"code"=> 'NGN',"symbol"=> "₦"],
["currency_id"=> "163","country_name"=> 'Niue (New Zealand)',"currency_name"=> 'New Zealand dollar',"code"=> 'NZD',"symbol"=> "$"],
["currency_id"=> "164","country_name"=> 'Norfolk Island (Australia)',"currency_name"=> 'Australian dollar',"code"=> 'AUD',"symbol"=> "$"],
["currency_id"=> "165","country_name"=> 'Northern Mariana Islands (USA)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "166","country_name"=> 'North Korea',"currency_name"=> 'North Korean won',"code"=> 'KPW',"symbol"=> "₩"],
["currency_id"=> "167","country_name"=> 'North Macedonia (formerly Macedonia)',"currency_name"=> 'Macedonian denar',"code"=> 'MKD',"symbol"=> "1"],
["currency_id"=> "168","country_name"=> 'Norway',"currency_name"=> 'Norwegian krone',"code"=> 'NOK',"symbol"=> "kr"],
["currency_id"=> "169","country_name"=> 'Oman',"currency_name"=> 'Omani rial',"code"=> 'OMR',"symbol"=> "ر.ع."],
["currency_id"=> "170","country_name"=> 'Pakistan',"currency_name"=> 'Pakistani rupee',"code"=> 'PKR',"symbol"=> "₨"],
["currency_id"=> "171","country_name"=> 'Palau',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "172","country_name"=> 'Palestine',"currency_name"=> 'Israeli new shekel',"code"=> 'ILS',"symbol"=> "₪"],
["currency_id"=> "173","country_name"=> 'Panama',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "174","country_name"=> 'Papua New Guinea',"currency_name"=> 'Papua New Guinean kina',"code"=> 'PGK',"symbol"=> "K"],
["currency_id"=> "175","country_name"=> 'Paraguay',"currency_name"=> 'Paraguayan guarani',"code"=> 'PYG',"symbol"=> "₲"],
["currency_id"=> "176","country_name"=> 'Peru',"currency_name"=> 'Peruvian sol',"code"=> 'PEN',"symbol"=> "S/."],
["currency_id"=> "177","country_name"=> 'Philippines',"currency_name"=> 'Philippine peso',"code"=> 'PHP',"symbol"=> "₱"],
["currency_id"=> "178","country_name"=> 'Pitcairn Islands (UK)',"currency_name"=> 'New Zealand dollar',"code"=> 'NZD',"symbol"=> "$"],
["currency_id"=> "179","country_name"=> 'Poland',"currency_name"=> 'Polish zloty',"code"=> 'PLN',"symbol"=> "zł"],
["currency_id"=> "180","country_name"=> 'Portugal',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "181","country_name"=> 'Puerto Rico (USA)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "182","country_name"=> 'Qatar',"currency_name"=> 'Qatari riyal',"code"=> 'QAR',"symbol"=> "ر.ق"],
["currency_id"=> "183","country_name"=> 'Reunion (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "184","country_name"=> 'Romania',"currency_name"=> 'Romanian leu',"code"=> 'RON',"symbol"=> "L"],
["currency_id"=> "185","country_name"=> 'Russia',"currency_name"=> 'Russian ruble',"code"=> 'RUB',"symbol"=> "р."],
["currency_id"=> "186","country_name"=> 'Rwanda',"currency_name"=> 'Rwandan franc',"code"=> 'RWF',"symbol"=> "₣"],
["currency_id"=> "187","country_name"=> 'Saba (Netherlands)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "188","country_name"=> 'Saint Barthelemy (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "189","country_name"=> 'Saint Helena (UK)',"currency_name"=> 'Saint Helena pound',"code"=> 'SHP',"symbol"=> "£"],
["currency_id"=> "190","country_name"=> 'Saint Kitts and Nevis',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "1"],
["currency_id"=> "191","country_name"=> 'Saint Lucia',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "$"],
["currency_id"=> "192","country_name"=> 'Saint Martin (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "193","country_name"=> 'Saint Pierre and Miquelon (France)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "194","country_name"=> 'Saint Vincent and the Grenadines',"currency_name"=> 'East Caribbean dollar',"code"=> 'XCD',"symbol"=> "$"],
["currency_id"=> "195","country_name"=> 'Samoa',"currency_name"=> 'Samoan tala',"code"=> 'WST',"symbol"=> "T"],
["currency_id"=> "196","country_name"=> 'San Marino',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "197","country_name"=> 'Sao Tome and Principe',"currency_name"=> 'Sao Tome and Principe dobra',"code"=> 'STN',"symbol"=> "Db"],
["currency_id"=> "198","country_name"=> 'Saudi Arabia',"currency_name"=> 'Saudi Arabian riyal',"code"=> 'SAR',"symbol"=> "ر.س"],
["currency_id"=> "199","country_name"=> 'Senegal',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "200","country_name"=> 'Serbia',"currency_name"=> 'Serbian dinar',"code"=> 'RSD',"symbol"=> "din"],
["currency_id"=> "201","country_name"=> 'Seychelles',"currency_name"=> 'Seychellois rupee',"code"=> 'SCR',"symbol"=> "₨"],
["currency_id"=> "202","country_name"=> 'Sierra Leone',"currency_name"=> 'Sierra Leonean leone',"code"=> 'SLL',"symbol"=> "Le"],
["currency_id"=> "203","country_name"=> 'Singapore',"currency_name"=> 'Singapore dollar',"code"=> 'SGD',"symbol"=> "$"],
["currency_id"=> "204","country_name"=> 'Sint Eustatius (Netherlands)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "205","country_name"=> 'Sint Maarten (Netherlands)',"currency_name"=> 'Netherlands Antillean guilder',"code"=> 'ANG',"symbol"=> "NAƒ"],
["currency_id"=> "206","country_name"=> 'Slovakia',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "207","country_name"=> 'Slovenia',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "208","country_name"=> 'Solomon Islands',"currency_name"=> 'Solomon Islands dollar',"code"=> 'SBD',"symbol"=> "$"],
["currency_id"=> "209","country_name"=> 'Somalia',"currency_name"=> 'Somali shilling',"code"=> 'SOS',"symbol"=> "Sh"],
["currency_id"=> "210","country_name"=> 'South Africa',"currency_name"=> 'South African rand',"code"=> 'ZAR',"symbol"=> "R"],
["currency_id"=> "211","country_name"=> 'South Georgia Island (UK)',"currency_name"=> 'Pound sterling',"code"=> 'GBP',"symbol"=> "£"],
["currency_id"=> "212","country_name"=> 'South Korea',"currency_name"=> 'South Korean won',"code"=> 'KRW',"symbol"=> "₩"],
["currency_id"=> "213","country_name"=> 'South Sudan',"currency_name"=> 'South Sudanese pound',"code"=> 'SSP',"symbol"=> "£"],
["currency_id"=> "214","country_name"=> 'Spain',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "215","country_name"=> 'Sri Lanka',"currency_name"=> 'Sri Lankan rupee',"code"=> 'LKR',"symbol"=> "Rs"],
["currency_id"=> "216","country_name"=> 'Sudan',"currency_name"=> 'Sudanese pound',"code"=> 'SDG',"symbol"=> "£"],
["currency_id"=> "217","country_name"=> 'Suriname',"currency_name"=> 'Surinamese dollar',"code"=> 'SRD',"symbol"=> "$"],
["currency_id"=> "218","country_name"=> 'Svalbard and Jan Mayen (Norway)',"currency_name"=> 'Norwegian krone',"code"=> 'NOK',"symbol"=> "kr"],
["currency_id"=> "219","country_name"=> 'Sweden',"currency_name"=> 'Swedish krona',"code"=> 'SEK',"symbol"=> "kr"],
["currency_id"=> "220","country_name"=> 'Switzerland',"currency_name"=> 'Swiss franc',"code"=> 'CHF',"symbol"=> "₣"],
["currency_id"=> "221","country_name"=> 'Syria',"currency_name"=> 'Syrian pound',"code"=> 'SYP',"symbol"=> "ل.س"],
["currency_id"=> "222","country_name"=> 'Taiwan',"currency_name"=> 'New Taiwan dollar',"code"=> 'TWD',"symbol"=> "$"],
["currency_id"=> "223","country_name"=> 'Tajikistan',"currency_name"=> 'Tajikistani somoni',"code"=> 'TJS',"symbol"=> "ЅМ"],
["currency_id"=> "224","country_name"=> 'Tanzania',"currency_name"=> 'Tanzanian shilling',"code"=> 'TZS',"symbol"=> "Sh"],
["currency_id"=> "225","country_name"=> 'Thailand',"currency_name"=> 'Thai baht',"code"=> 'THB',"symbol"=> "฿"],
["currency_id"=> "226","country_name"=> 'Timor-Leste',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "227","country_name"=> 'Togo',"currency_name"=> 'West African CFA franc',"code"=> 'XOF',"symbol"=> "CFA"],
["currency_id"=> "228","country_name"=> 'Tokelau (New Zealand)',"currency_name"=> 'New Zealand dollar',"code"=> 'NZD',"symbol"=> "$"],
["currency_id"=> "229","country_name"=> 'Tonga',"currency_name"=> 'Tongan pa’anga',"code"=> 'TOP',"symbol"=> "T$"],
["currency_id"=> "230","country_name"=> 'Trinidad and Tobago',"currency_name"=> 'Trinidad and Tobago dollar',"code"=> 'TTD',"symbol"=> "$"],
["currency_id"=> "231","country_name"=> 'Tristan da Cunha (UK)',"currency_name"=> 'Pound sterling',"code"=> 'GBP',"symbol"=> "£"],
["currency_id"=> "232","country_name"=> 'Tunisia',"currency_name"=> 'Tunisian dinar',"code"=> 'TND',"symbol"=> "د.ت"],
["currency_id"=> "233","country_name"=> 'Turkey',"currency_name"=> 'Turkish lira',"code"=> 'TRY',"symbol"=> "₤"],
["currency_id"=> "234","country_name"=> 'Turkmenistan',"currency_name"=> 'Turkmen manat',"code"=> 'TMT',"symbol"=> "m"],
["currency_id"=> "235","country_name"=> 'Turks and Caicos Islands (UK)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "236","country_name"=> 'Tuvalu',"currency_name"=> 'Australian dollar',"code"=> 'AUD',"symbol"=> "$"],
["currency_id"=> "237","country_name"=> 'Uganda',"currency_name"=> 'Ugandan shilling',"code"=> 'UGX',"symbol"=> "Sh"],
["currency_id"=> "238","country_name"=> 'Ukraine',"currency_name"=> 'Ukrainian hryvnia',"code"=> 'UAH',"symbol"=> "₴"],
["currency_id"=> "239","country_name"=> 'United Arab Emirates',"currency_name"=> 'UAE dirham',"code"=> 'AED',"symbol"=> "د.إ"],
["currency_id"=> "240","country_name"=> 'United Kingdom',"currency_name"=> 'Pound sterling',"code"=> 'GBP',"symbol"=> "£"],
["currency_id"=> "241","country_name"=> 'United States of America',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "242","country_name"=> 'Uruguay',"currency_name"=> 'Uruguayan peso',"code"=> 'UYU',"symbol"=> "$"],
["currency_id"=> "243","country_name"=> 'US Virgin Islands (USA)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "244","country_name"=> 'Uzbekistan',"currency_name"=> 'Uzbekistani som',"code"=> 'UZS',"symbol"=> "so'm"],
["currency_id"=> "245","country_name"=> 'Vanuatu',"currency_name"=> 'Vanuatu vatu',"code"=> 'VUV',"symbol"=> "Vt"],
["currency_id"=> "246","country_name"=> 'Vatican City (Holy See)',"currency_name"=> 'European euro',"code"=> 'EUR',"symbol"=> "€"],
["currency_id"=> "247","country_name"=> 'Venezuela',"currency_name"=> 'Venezuelan bolivar',"code"=> 'VES',"symbol"=> "ރ."],
["currency_id"=> "248","country_name"=> 'Vietnam',"currency_name"=> 'Vietnamese dong',"code"=> 'VND',"symbol"=> "₫"],
["currency_id"=> "249","country_name"=> 'Wake Island (USA)',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
["currency_id"=> "250","country_name"=> 'Wallis and Futuna (France)',"currency_name"=> 'CFP franc',"code"=> 'XPF',"symbol"=> "₣"],
["currency_id"=> "251","country_name"=> 'Yemen',"currency_name"=> 'Yemeni rial',"code"=> 'YER',"symbol"=> "﷼"],
["currency_id"=> "252","country_name"=> 'Zambia',"currency_name"=> 'Zambian kwacha',"code"=> 'ZMW',"symbol"=> "ZK"],
["currency_id"=> "253","country_name"=> 'Zimbabwe',"currency_name"=> 'United States dollar',"code"=> 'USD',"symbol"=> "$"],
]
];