<?php

return [
    "ears" =>
    [
        ["ear_id" => "1", "ear_name" => 'Attached Lobe', "ear_color" => '#ECBCB4', "ear_description" => 'These types of earlobes are not rare, but are also not commonly found. Earlobes of such type are small in size and do not have hangs. They are attached directly to the side of the head. The structural formation of this kind of lobe is due to the absence of the dominant allele in the chromosomes.', 'ear_img' => 'attached_lobe_11072020_1594471137.jpg', 'status' => 1],
        ["ear_id" => "2", "ear_name" => 'Broad Lobe', "ear_color" => '#ECBCB4', "ear_description" => 'People with broad ears tend to be very open and laid back people. They like to take life as it comes and do not really mind letting go of things easily. They also tend to be extroverts and get along with people more, as they are funny and amiable people. ', 'ear_img' => 'broad_lobe_11072020_1594471152.jpg', 'status' => 1],
        ["ear_id" => "3", "ear_name" => 'Narrow', "ear_color" => '#ECBCB4', "ear_description" => 'Narrow-eared people are quiet people, who take their time and think twice before they speak. But once they do speak, it usually hits the nail on the head. They don not like idle gossip and small talk, and prefer having long, meaningful conversations. ', 'ear_img' => 'narrow_11072020_1594471165.jpg', 'status' => 1],
        ["ear_id" => "4", "ear_name" => 'Pointed', "ear_color" => '#ECBCB4', "ear_description" => 'People with pointed ears are like Sherlock Holmes — highly perceptive, observant, and perfectionists. They are the people who notice things that others do not and quick to respond with a witty line. They also tend to dwell on things, as they want everything to be just right.', 'ear_img' => 'pointed_11072020_1594471183.jpg', 'status' => 1],
        ["ear_id" => "5", "ear_name" => 'Round Ear Free Lobe', "ear_color" => '#ECBCB4', "ear_description" => 'Round-eared people are the ones you can depend on for everything. They are very loyal and expect the same kind of loyalty from those close to them. This also means that they take betrayal (even small ones) to heart, and do not forgive easily. ', 'ear_img' => 'round_ear_free_lobe_11072020_1594471195.jpg', 'status' => 1],
        ["ear_id" => "6", "ear_name" => 'Square', "ear_color" => '#ECBCB4', "ear_description" => 'This uncommon shape indicate high levels of creativity and intellect. They love creating and the more complex a concept, the better for them. They also tend have very high standards, and do not let just anyone in — you have to be considered special.', 'ear_img' => 'square_11072020_1594471210.jpg', 'status' => 1],
        ["ear_id" => "7", "ear_name" => 'Sticking Out', "ear_color" => '#ECBCB4', "ear_description" => 'Even though they tend to be the butt of many jokes, these people are the best. They are super friendly and unique — basically, you are never bored around them. However, they also do tend to have very different ideas, which makes it hard for people to understand them sometimes.', 'ear_img' => 'stickingout_11072020_1594469780.jpg', 'status' => 1],
    ],
];
