<?php

return [
    "eyes" =>
    [
        ["eye_id" => "1", "eye_name" => 'Almond Hooded Deepset', "eye_color" => '#000000', "eye_description" => 'Almond-shaped eyes have a smaller eyelid and are longer in width than they are round — just like an almond!This eye shape tapers to a point by the tear duct and the outer eye.The outer part of the cornea is generally hidden under the top and bottom lids. There is also an apparent crease.Hooded eyes feature a heavy brow bone with a deep-set crease.When hooded eyes are open, the eyelid is not generally visible and retracts into the crease.As you have aged, your eyelid space has diminished, taking on a hooded appearance.', 'eye_img' => 'AlmondHoodedDeepset_12072020_1594539732.png', 'status' => 1],
        ["eye_id" => "2", "eye_name" => 'Almond Monolid Portruding', "eye_color" => '#000000', "eye_description" => 'Almond-shaped eyes have a smaller eyelid and are longer in width than they are round — just like an almond!This eye shape tapers to a point by the tear duct and the outer eye.The outer part of the cornea is generally hidden under the top and bottom lids. There is also an apparent crease.Common in Asian women, monolid eyes feature a less apparent crease.Often called a shallow or smooth eyelid, monolids don not reveal as much if any of the eyelid.', 'eye_img' => 'AlmondMonolidPortruding_12072020_1594539830.png', 'status' => 1],
        ["eye_id" => "3", "eye_name" => 'Almond Parallel Deepset', "eye_color" => '#000000', "eye_description" => 'Almond-shaped eyes have a smaller eyelid and are longer in width than they are round — just like an almond!This eye shape tapers to a point by the tear duct and the outer eye.The outer part of the cornea is generally hidden under the top and bottom lids. There is also an apparent crease.', 'eye_img' => 'AlmondParallelDeepset_12072020_1594539887.png', 'status' => 1],
        ["eye_id" => "4", "eye_name" => 'Almond Parallel Portruding', "eye_color" => '#000000', "eye_description" => 'Almond-shaped eyes have a smaller eyelid and are longer in width than they are round — just like an almond!This eye shape tapers to a point by the tear duct and the outer eye.The outer part of the cornea is generally hidden under the top and bottom lids. There is also an apparent crease.', 'eye_img' => 'AlmondParallelPortruding_12072020_1594539939.png', 'status' => 1],
        ["eye_id" => "5", "eye_name" => 'Almond Tapered Deepset', "eye_color" => '#000000', "eye_description" => 'Almond-shaped eyes have a smaller eyelid and are longer in width than they are round — just like an almond!This eye shape tapers to a point by the tear duct and the outer eye.The outer part of the cornea is generally hidden under the top and bottom lids. There is also an apparent crease.', 'eye_img' => 'AlmondTaperedDeepset_12072020_1594539984.png', 'status' => 1],
        ["eye_id" => "6", "eye_name" => 'Almond Tapered Portruding', "eye_color" => '#000000', "eye_description" => 'Almond-shaped eyes have a smaller eyelid and are longer in width than they are round — just like an almond!This eye shape tapers to a point by the tear duct and the outer eye.The outer part of the cornea is generally hidden under the top and bottom lids. There is also an apparent crease.', 'eye_img' => 'AlmondTaperedPortruding_12072020_1594540023.png', 'status' => 1],
        ["eye_id" => "7", "eye_name" => 'Downturned Hooded Deepset', "eye_color" => '#000000', "eye_description" => 'The outer corners of downturned eyes are lower than the inner corner.Also known as a "descending eyelid," downturned eyes feature an upper lid that dips to meet the lower lash line.Hooded eyes feature a heavy brow bone with a deep-set crease.When hooded eyes are open, the eyelid is not generally visible and retracts into the crease.As you have aged, your eyelid space has diminished, taking on a hooded appearance.', 'eye_img' => 'DownturnedHoodedDeepset_12072020_1594540091.png', 'status' => 1],
        ["eye_id" => "8", "eye_name" => 'Downturned Monolid Portruding', "eye_color" => '#000000', "eye_description" => 'The outer corners of downturned eyes are lower than the inner corner.Also known as a "descending eyelid," downturned eyes feature an upper lid that dips to meet the lower lash line.Common in Asian women, monolid eyes feature a less apparent crease.Often called a shallow or smooth eyelid, monolids don not reveal as much if any of the eyelid.', 'eye_img' => 'DownturnedMonolidPortruding_12072020_1594540134.png', 'status' => 1],
        ["eye_id" => "9", "eye_name" => 'Downturned Parallel Deepset', "eye_color" => '#000000', "eye_description" => 'The outer corners of downturned eyes are lower than the inner corner.Also known as a "descending eyelid," downturned eyes feature an upper lid that dips to meet the lower lash line.Common in Asian women, monolid eyes feature a less apparent crease.Often called a shallow or smooth eyelid, monolids don not reveal as much if any of the eyelid.', 'eye_img' => 'DownturnedParallelDeepset_12072020_1594540183.png', 'status' => 1],
        ["eye_id" => "10", "eye_name" => 'Downturned Tapered Portruding', "eye_color" => '#000000', "eye_description" => 'The outer corners of downturned eyes are lower than the inner corner.Also known as a "descending eyelid," downturned eyes feature an upper lid that dips to meet the lower lash line.', 'eye_img' => 'DownturnedTaperedPortruding_12072020_1594540235.png', 'status' => 1],
        ["eye_id" => "11", "eye_name" => 'Round Hooded Deepset', "eye_color" => '#000000', "eye_description" => 'Round eyes are usually large, prominent and look more circular.The cornea of round eyes is surrounded by white all the way around.The inner and outer corners of round eyes are rounded and not pulled inward or outward.Hooded eyes feature a heavy brow bone with a deep-set crease.When hooded eyes are open, the eyelid is not generally visible and retracts into the crease.As you have aged, your eyelid space has diminished, taking on a hooded appearance.', 'eye_img' => 'RoundHoodedDeepset_12072020_1594540301.png', 'status' => 1],
        ["eye_id" => "12", "eye_name" => 'Round Monolid Portruding', "eye_color" => '#000000', "eye_description" => 'Round eyes are usually large, prominent and look more circular.The cornea of round eyes is surrounded by white all the way around.The inner and outer corners of round eyes are rounded and not pulled inward or outward.Common in Asian women, monolid eyes feature a less apparent crease.Often called a shallow or smooth eyelid, monolids don not reveal as much if any of the eyelid.', 'eye_img' => 'RoundMonolidPortruding_12072020_1594540344.png', 'status' => 1],
        ["eye_id" => "13", "eye_name" => 'Round Parallel Deepset', "eye_color" => '#000000', "eye_description" => 'Round eyes are usually large, prominent and look more circular.The cornea of round eyes is surrounded by white all the way around.The inner and outer corners of round eyes are rounded and not pulled inward or outward.', 'eye_img' => 'RoundParallelDeepset_12072020_1594540385.png', 'status' => 1],
        ["eye_id" => "14", "eye_name" => 'Round Parallel Portruding', "eye_color" => '#000000', "eye_description" => 'Round eyes are usually large, prominent and look more circular.The cornea of round eyes is surrounded by white all the way around.The inner and outer corners of round eyes are rounded and not pulled inward or outward.', 'eye_img' => 'RoundParallelPortruding_12072020_1594540438.png', 'status' => 1],
        ["eye_id" => "15", "eye_name" => 'Round Trapered Portruding', "eye_color" => '#000000', "eye_description" => 'Round eyes are usually large, prominent and look more circular.The cornea of round eyes is surrounded by white all the way around.The inner and outer corners of round eyes are rounded and not pulled inward or outward.', 'eye_img' => 'RoundTraperedPortruding_12072020_1594540500.png', 'status' => 1],
        ["eye_id" => "16", "eye_name" => 'Upturned Monolid Portruding', "eye_color" => '#000000', "eye_description" => 'Basically the opposite of downturned eyes, upturned eyes have outer corners that turn upward and are higher than the inner corner.Also known as "cat eyes," upturned eyes tilt upward, giving the eye an exotic appearance. Ask yourself if you look like you have had an eye lift!,Common in Asian women, monolid eyes feature a less apparent crease.Often called a shallow or smooth eyelid, monolids don not reveal as much if any of the eyelid.', 'eye_img' => 'UpturnedMonolidPortruding_12072020_1594540544.png', 'status' => 1],
        ["eye_id" => "17", "eye_name" => 'Upturned Parallel Deepset', "eye_color" => '#000000', "eye_description" => 'The bottom lash line of upturned eyes curves upward to meet the top lashes at the outer corner of the eye.', 'eye_img' => 'UpturnedParallelDeepset_12072020_1594540585.png', 'status' => 1],
        ["eye_id" => "18", "eye_name" => 'Upturned Parallel Portruding', "eye_color" => '#000000', "eye_description" => 'The bottom lash line of upturned eyes curves upward to meet the top lashes at the outer corner of the eye.', 'eye_img' => 'UpturnedParallelPortruding_12072020_1594540626.png', 'status' => 1],
        ["eye_id" => "19", "eye_name" => 'Upturned Tapered Portruding', "eye_color" => '#000000', "eye_description" => 'The bottom lash line of upturned eyes curves upward to meet the top lashes at the outer corner of the eye.', 'eye_img' => 'UpturnedTaperedPortruding_12072020_1594540662.png', 'status' => 1]
    ],
];
