<?php

return [
    "hairs" =>
    [
        ["hair_id" => "1", "hair_style_name" => 'Bald', "hair_color" => '#000000', "hair_description" => 'Bald men with long hair may prefer to find longer hairstyles to try. While it may seem counter-intuitive, hiding bald spots with long hair is actually harder unless you also have thick hair.', 'hair_img' => 'Bald_13072020_1594652430.png', 'status' => 1],
        ["hair_id" => "2", "hair_style_name" => 'Bob', "hair_color" => '#000000', "hair_description" => 'A bob cut, also known as a bob, is a short- to medium-length haircut, in which the hair is typically cut straight around the head at about jaw-level, often with a fringe at the front. The standard bob is normally cut either between or just below the tips of the ears, and well above the shoulders.', 'hair_img' => 'Bob_13072020_1594652485.png', 'status' => 1],
        ["hair_id" => "3", "hair_style_name" => 'Breadlocks', "hair_color" => '#000000', "hair_description" => 'Dreadlocks continue to be popular in barbershops. Also known as locs, dreads epitomize a free, independent, and bohemian lifestyle; although guys shouldn’t let the stereotype prevent them from rocking dread hairstyles if that’s what they want. And while dreadlock styles are usually worn by black men, guys of all races have embraced the look. From short to long, black to blonde, and straight to braided, men’s dread styles come in many unique shapes, sizes, and designs.', 'hair_img' => 'Breadlocks_13072020_1594652495.png', 'status' => 1],
        ["hair_id" => "4", "hair_style_name" => 'Bun', "hair_color" => '#000000', "hair_description" => 'The man bun is a simple hairstyle to get, but it requires regular maintenance to make sure it doesn’t get too greasy or unhealthy. Most hair experts recommend washing your hair a maximum of two or three times a week because shampoos strip your hair of its natural oils. To have the healthiest hair possible, only shampoo your hair every few days.', 'hair_img' => 'Bun_13072020_1594652504.png', 'status' => 1],
        ["hair_id" => "5", "hair_style_name" => 'Combover', "hair_color" => '#000000', "hair_description" => 'The comb over fade combines the classic side-swept look with very short hair on the sides. The fade involves tapering the hair towards the neck, so that your hair gets gradually shorter lower down your sides and back. The technique creates a fresh, high-contrast look, especially when combined with a smooth and timeless haircut such as the comb over.', 'hair_img' => 'Combover_13072020_1594652517.png', 'status' => 1],
        ["hair_id" => "6", "hair_style_name" => 'Curly Hair-1', "hair_color" => '#000000', "hair_description" => 'Curly hair looks fabulous, when treated right, but need a lot of patience and love to maintain. Untangling knots or the time needed to air-dry make loving this hair-type difficult at times, but on the upside, even a simple ponytail looks absolutely stunning it those curl springing out. ', 'hair_img' => 'CurlyHair_13072020_1594652528.png', 'status' => 1],
        ["hair_id" => "7", "hair_style_name" => 'Curly Hair-2', "hair_color" => '#000000', "hair_description" => 'Curly hair looks fabulous, when treated right, but need a lot of patience and love to maintain. Untangling knots or the time needed to air-dry make loving this hair-type difficult at times, but on the upside, even a simple ponytail looks absolutely stunning it those curl springing out. ', 'hair_img' => 'Curly_13072020_1594652538.png', 'status' => 1],
        ["hair_id" => "8", "hair_style_name" => 'Dyed Hair', "hair_color" => '#000000', "hair_description" => 'hair dyeing, is the practice of changing the hair color. The main reasons for this are cosmetic: to cover gray or white hair, to change to a color regarded as more fashionable or desirable, or to restore the original hair color after it has been discolored by hairdressing processes or sun bleaching', 'hair_img' => 'DyedHair_13072020_1594652552.png', 'status' => 1],
        ["hair_id" => "9", "hair_style_name" => 'Fringe', "hair_color" => '#000000', "hair_description" => 'A fringe lets us correct our face shape and introduce something new into our hairstyles. It looks equally great with long, medium or short lengths, so you may stick to your preferred cut, but refresh it with a new twist at the expense of classy bangs. The length, style and finish for your fringe may vary.', 'hair_img' => 'Fringe_13072020_1594652564.png', 'status' => 1],
        ["hair_id" => "10", "hair_style_name" => 'Gray Hair', "hair_color" => '#000000', "hair_description" => 'When it comes to medium hairstyles for gray hair, nothing looks more sophisticated than highlights and lowlights. They create a modern, youthful color, guaranteed to give others major hair envy.', 'hair_img' => 'GrayHair_13072020_1594652578.png', 'status' => 1],
        ["hair_id" => "11", "hair_style_name" => 'Long Blonde', "hair_color" => '#000000', "hair_description" => 'Long blonde hair is super popular among women of all age. Many women who lack naturally blonde hair will strive to dye their hair a beautiful blonde color. There are even jokes about how blondes have more fun! Give blonde hair a try to find out if the rumors are true.', 'hair_img' => 'LongBlonde_13072020_1594652605.png', 'status' => 1],
        ["hair_id" => "12", "hair_style_name" => 'Long Hair-1', "hair_color" => '#000000', "hair_description" => 'Long hairstyles with loose locks are generally very flattering for round faces. Straight tresses on both sides of your face cover it partially, and it seems narrower. Besides, they create long vertical lines next to your cute full face, elongating it visually to your advantage. Waves and curls also conceal the fullness of a round face, although they shouldn’t make any excessive volume on the sides.', 'hair_img' => 'LongHair_13072020_1594652622.png', 'status' => 1],
        ["hair_id" => "13", "hair_style_name" => 'Long Wavy Hair', "hair_color" => '#000000', "hair_description" => 'wavy hair is equally referred to as a blessing and a trouble. Curls do not always settle as you’d like them to, get extremely voluminous or simply stick out whimsically. Does it mean you should make good friends with a flat iron? Well, it’s quite tiresome to struggle with the curly structure of your hair on a daily basis, especially in wet weather. So wouldn’t it be better to look for more convenient, on-trend hairstyles, flattering for your face and suitable for your life style? Here are 60 stylish hairstyles for curly hair you can adopt for your chic looks.', 'hair_img' => 'LongWavyHair_13072020_1594652678.png', 'status' => 1],
        ["hair_id" => "14", "hair_style_name" => 'Long Hair-2', "hair_color" => '#000000', "hair_description" => 'Long hair and bangs is a winning duo and an excellent way to change your look, believe us. Bangs are so versatile that they can turn any boring hairstyle into a pretty one. Do we really don’t need to tell how adorable your updos, braids and half up half down hair look with a fringe cut? We don’t think so! Take your pick from the wispy, curtain, parted or baby bangs and add it little edge to your hairdos.', 'hair_img' => 'Long_13072020_1594652638.png', 'status' => 1],
        ["hair_id" => "15", "hair_style_name" => 'Man Bun', "hair_color" => '#000000', "hair_description" => 'The man bun hairstyle ascended as an edgy, fashionable alternative to wearing men’s long hair naturally. The man bun haircut is styled by grasping all of your hair at the crown of your head and then using a hair band or tie to fashion the hair into the bun. The best man buns generally requires at least 10 inches of hair to comfortably tie up. This means that most guys will need to grow long hair over the course of several months in order to do a man bun. However, the man bun has many different variations.', 'hair_img' => 'ManBun_13072020_1594652694.png', 'status' => 1],
        ["hair_id" => "16", "hair_style_name" => 'Medium Length', "hair_color" => '#000000', "hair_description" => 'Medium length hair once had a lackluster, status quo connotation—it was the choice cut for someone who simply couldn’t decide between ultra long and dramatically short hair. Then, something shifted. Enough celebrities and influencers have taken the shoulder length chop route to rewrite its definition. Nowadays, medium length hairstyles have a touch more edge than their predecessors. They’re cut on a slight angle for subtle movement; they’re offset with baby bangs for an alt-chic look; they’re gently curled for a tousled nineties vibe.', 'hair_img' => 'MediumLength_13072020_1594652709.png', 'status' => 1],
        ["hair_id" => "17", "hair_style_name" => 'Mohawk', "hair_color" => '#000000', "hair_description" => 'The mohawk (also referred to as a mohican) is a hairstyle in which, in the most common variety, both sides of the head are shaven, leaving a strip of noticeably longer hair in the center. The mohawk is also sometimes referred to as an iro in reference to the Iroquois (who include the Mohawk people), from whom the hairstyle is supposedly derived – though historically the hair was plucked out rather than shaved. Additionally, hairstyles bearing these names more closely resemble those worn by the Pawnee, rather than the Mohawk, Mohicans, Mohegan, or other groups whose names are phonetically similar.', 'hair_img' => 'Mohawk_13072020_1594652723.png', 'status' => 1],
        ["hair_id" => "18", "hair_style_name" => 'Pigtail', "hair_color" => '#000000', "hair_description" => 'Pigtails might seem like something that should be left back in childhood. However, this is exactly the reason why pigtails should be sported any time you feel like making them. This hairstyle will make any woman look fresh, young, and spunky.', 'hair_img' => 'Pigtail_13072020_1594652737.png', 'status' => 1],
        ["hair_id" => "19", "hair_style_name" => 'Pixel Cut', "hair_color" => '#000000', "hair_description" => 'A pixie haircut is a great solution for a contemporary woman on the go. It’s convenient, pretty and appropriate for hair of any type. Pixie haircuts for thick hair are full of texture and manageable volume. If your hair is fine, you may also choose the right pixie hair cut that adds dimension and boosts thickness of your short locks. Modern pixie cut styles are not limited to modest boyish ‘dos. You may indulge in a variety of pixie hairstyles with slicked back or tousled hair, try short pixie hairstyles for curly hair, asymmetrical vintage ‘dos or funky Faux Hawks.', 'hair_img' => 'PixelCut_13072020_1594652752.png', 'status' => 1],
        ["hair_id" => "20", "hair_style_name" => 'Plaits', "hair_color" => '#000000', "hair_description" => 'Plait is defined as to weave or braid. An example of plait is weaving in hair extensions.', 'hair_img' => 'Plaits_13072020_1594652765.png', 'status' => 1],
        ["hair_id" => "21", "hair_style_name" => 'Ponytail', "hair_color" => '#000000', "hair_description" => 'A ponytail is a hairstyle in which some, most or all of the hair on the head is pulled away from the face, gathered and secured at the back of the head with a hair tie, clip, or other similar device and allowed to hang freely from that point. It gets its name from its resemblance to the tail of a pony.', 'hair_img' => 'Ponytail_13072020_1594652784.png', 'status' => 1],
        ["hair_id" => "22", "hair_style_name" => 'Red Hair', "hair_color" => '#000000', "hair_description" => 'Red hair color has never been hotter. Call it the Shiv Roy effect or point to any number of celebrities who recently took the copper plunge—Zendaya, Anne Hathaway, Zoey Deutch—the fact of the matter is that there are more gorgeous takes on the shade than ever before. And they have got the names (however ridiculous they may be) to prove it: mulled wine, peach cobbler, sangria spice…the list goes on.', 'hair_img' => 'RedHair_13072020_1594652806.png', 'status' => 1],
        ["hair_id" => "23", "hair_style_name" => 'Ringlets', "hair_color" => '#000000', "hair_description" => 'A ringlet is a type of hairstyle. Ringlets are often also known as princess curls or corkscrew curls. It is achieved by wrapping a lock of hair around the length of a thin curling iron or can be done naturally by people with sufficiently tightly curled hair. The curls can also be achieved by hair rollers. Loose ringlets can be created just by twisting wet hair as well.', 'hair_img' => 'Ringlets_13072020_1594652822.png', 'status' => 1],
        ["hair_id" => "24", "hair_style_name" => 'Short Blonde', "hair_color" => '#000000', "hair_description" => 'Short blonde hair is when hair is cut short and colored a shade of blonde. There are many short lengths to choose from such as a short pixie to neck-length. There’s also a wide range of blonde shades to add as either a full-color dye or highlights. The most popular short haircut for women right now is a neck-length layered bob. As for color, a platinum or ash blonde hue is totally trending this season.', 'hair_img' => 'ShortBlonde_13072020_1594652865.png', 'status' => 1],
        ["hair_id" => "25", "hair_style_name" => 'Short', "hair_color" => '#000000', "hair_description" => 'Short hair refers to any haircut with little length. It may vary from above the ears to below the chin. If a man hair reaches the chin, it may not be considered short. For a woman, however, short varies from close-cropped to just above the shoulders.', 'hair_img' => 'Short_13072020_1594652845.png', 'status' => 1],
        ["hair_id" => "26", "hair_style_name" => 'Straight', "hair_color" => '#000000', "hair_description" => 'straight hair is fine hair. It’s soft, shiny, and wispy. It looks and feels “perfect” but often lacks volume. If you have this kind of straight hair, you can follow any of the styling tips for thin hair (such as a layered cut and color.)', 'hair_img' => 'Straight_13072020_1594652922.png', 'status' => 1],
        ["hair_id" => "27", "hair_style_name" => 'Waved', "hair_color" => '#000000', "hair_description" => 'Wavy hair, for many women, is the ultimate look. Those lucky women who sport this look naturally really have hit the jackpot hair-wise.', 'hair_img' => 'Waved_13072020_1594652937.png', 'status' => 1],
    ],
];
