<?php

return [
    "noses" =>
    [
        ["nose_id" => "1", "nose_name" => 'Aquiline', "nose_color" => '#ECBCB4', "nose_description" => 'An aquiline nose is a human nose with a prominent bridge, giving it the appearance of being curved or slightly bent. The word aquiline comes from the Latin word aquilinus, an allusion to the curved beak of an eagle.', 'nose_img' => 'Aquiline_18072020_1595068449.png', 'status' => 1],
        ["nose_id" => "2", "nose_name" => 'Button', "nose_color" => '#ECBCB4', "nose_description" => 'Button nose (plural button noses) (idiomatic) A nose with a small size and a relatively flat, round shape, usually considered to be dainty or cute in appearance. (idiomatic) A person having such a nose.', 'nose_img' => 'Button_18072020_1595068463.png', 'status' => 1],
        ["nose_id" => "3", "nose_name" => 'Droopy', "nose_color" => '#ECBCB4', "nose_description" => 'A droopy nose is the name given for a nose that hooks downward or is elongated, similar to how a witch is depicted. Also referred to as nasal tip ptosis, this drooping is caused by a lack or loss of structure on the nasal tip which is what supports the nasal tip.', 'nose_img' => 'Droopy_18072020_1595068504.png', 'status' => 1],
        ["nose_id" => "4", "nose_name" => 'Funnel', "nose_color" => '#ECBCB4', "nose_description" => 'There are some basic nose shapes that tend to match different ethnic groups, but again, almost all noses can be found in most ethnic groups. There are some exceptions to this, for example what’s known as the ‘funnel’ nose found in many Africans is never found in Caucasians, but in turn it is also not always found in Africans either; and Asian noses are usually small with a low bridge. We have the hooked, droopy, aquiline, Roman, grecian, upturned, snub, button and funnel nose shapes. Nose shape can be altered either surgically', 'nose_img' => 'Funnel_18072020_1595068520.png', 'status' => 1],
        ["nose_id" => "5", "nose_name" => 'Grecian', "nose_color" => '#ECBCB4', "nose_description" => 'A straight nose that continues the line of the forehead without a dip.', 'nose_img' => 'Grecian_18072020_1595068574.png', 'status' => 1],
        ["nose_id" => "6", "nose_name" => 'Hooked', "nose_color" => '#ECBCB4', "nose_description" => 'A hooked nose is a description of a type of nose that is curved or has a bump on the bridge, giving the appearance of a hooked shape. There can be many factors which can cause a nose to become hooked, it could be a result of a broken nose or some other genetic factor.', 'nose_img' => 'Hooked_18072020_1595068587.png', 'status' => 1],
        ["nose_id" => "7", "nose_name" => 'Snub', "nose_color" => '#ECBCB4', "nose_description" => 'a Snub nose that is short and turns upwards at the end', 'nose_img' => 'Snub_18072020_1595068609.png', 'status' => 1],
        ["nose_id" => "8", "nose_name" => 'Upturned', "nose_color" => '#ECBCB4', "nose_description" => 'An upturned nose refers to a nose in which the tip is angled upward. Although a turned up nose may function normally, it sometimes makes a person nose appear small, as well as makes the nostrils prominent. Oftentimes, an upturned nose is inherited from family.', 'nose_img' => 'Upturned_18072020_1595068625.png', 'status' => 1],
    ],
];
